from .user import User
from .program import Program
from .registration import Registration
from .module import Module
from .leave import Leave
from .module_class import Class
from .rolecall import RoleCall
from .file import File
from .task import Task
from .submitted_task import SubmittedTask
from .submitted_file import SubmittedFile
from .activity import Activity