# Generated by Django 5.1.7 on 2025-04-24 15:36

import django.db.models.deletion
import sum_app.models.admin
import sum_app.models.file
import sum_app.models.module
import sum_app.models.program
import sum_app.models.task
import sum_app.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone_no', models.CharField(max_length=225, null=True, validators=[sum_app.models.admin.validate_phone_no])),
                ('authority', models.IntegerField(
                    choices=[(1, 'Super User'), (2, 'Editor'), (3, 'Moderator')],
                    default=3
                )),
                ('admin_code', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.IntegerField(null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'admins',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('original_name', models.CharField(max_length=225)),
                ('type', models.IntegerField()),
                ('size', models.IntegerField(null=True, validators=[sum_app.models.file.validate_file_size])),
                ('url', models.CharField(max_length=225)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.IntegerField(null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'files',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('module_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('module_code', models.CharField(max_length=50)),
                ('credit', models.SmallIntegerField(validators=[sum_app.models.module.validate_positive_credit])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.IntegerField(null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'modules',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('program_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('program_code', models.CharField(max_length=255, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('fees', models.IntegerField(null=True, validators=[sum_app.models.program.validate_positive_fees])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.IntegerField(null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'programs',
            },
        ),
        migrations.CreateModel(
            name='SubmittedTask',
            fields=[
                ('submitted_task_id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('checked_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.IntegerField(null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'submitted_tasks',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('phone_no', models.CharField(max_length=225, null=True, validators=[sum_app.models.user.validate_phone_no])),
                ('is_teacher', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('user_code', models.CharField(max_length=50, unique=True, null=True, blank=True)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.IntegerField(null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=225)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('canceled', models.BooleanField(default=False)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sum_app.module')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.IntegerField(null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'classes',
            },
        ),
        migrations.AddField(
            model_name='module',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sum_app.program'),
        ),
        migrations.CreateModel(
            name='SubmittedFile',
            fields=[
                ('submitted_file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sum_app.file')),
                ('submitted_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sum_app.submittedtask')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.IntegerField(null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'submitted_files',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('type', models.IntegerField(choices=[(1, 'Assignment'), (2, 'Tutorial')])),
                ('max_score', models.IntegerField(default=100, validators=[sum_app.models.task.validate_positive])),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sum_app.file')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='sum_app.module')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.IntegerField(null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tasks',
            },
        ),
        migrations.AddField(
            model_name='submittedtask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sum_app.task'),
        ),
        migrations.AddField(
            model_name='submittedtask',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sum_app.user'),
        ),
        migrations.AddField(
            model_name='module',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sum_app.user'),
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('leave_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('approve_status', models.BooleanField(default=False)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sum_app.program')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sum_app.user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.IntegerField(null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'leaves',
            },
        ),
        migrations.CreateModel(
            name='RoleCall',
            fields=[
                ('rolecall_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(
                    choices=[(1, 'Present'), (2, 'Absent'), (3, 'Leave')]
                )),
                ('class_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sum_app.class')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sum_app.user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.IntegerField(null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rolecalls',
                'unique_together': {('user', 'class_field')},
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('registration_id', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=50, null=True, blank=True)),
                ('student_code', models.CharField(max_length=50, unique=True, null=True, blank=True)),
                ('scholared', models.BooleanField(default=False)),
                ('teacher_flag', models.BooleanField(default=False)),
                ('payment_status', models.IntegerField(choices=[(0, 'Not Paid'), (1, 'Paying'), (2, 'Paid'), (3, '-')], default=0)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sum_app.program')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sum_app.user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.IntegerField(null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'registrations',
                'unique_together': {('user', 'program')},
            },
        ),
    ]
