# Generated by Django 5.1.7 on 2025-05-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sum_app', '0002_alter_admin_admin_code_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
